---
deployment:
  tasks:
    - /bin/bash <<'DEPLOY'
      set -euo pipefail
      log(){ printf '[deploy] %s\n' "$*"; }
      log "Starting deploy: $(date -Is)"
      SRC="${DEPLOYMENT_SOURCE}"
      DST="${DEPLOYMENT_TARGET}"
      HOME="/home/${USER}"

      # Persistent storage for uploads
      mkdir -p "$HOME/SiteStorage/media" "$HOME/SiteStorage/video"
      [ -L "$DST/media" ] || ln -s "$HOME/SiteStorage/media" "$DST/media"
      [ -L "$DST/video" ] || ln -s "$HOME/SiteStorage/video" "$DST/video"

      log "Rsync code -> ${DST}"
      # Use a timeout so the job can never hang indefinitely.
      timeout 900 rsync -a --delete-after         --exclude='media/' --exclude='video/' --exclude='uploads/'         --human-readable --info=stats2,progress2         "$SRC/public/" "$DST/"

      log "Fix permissions (no descent into symlinked storage)"
      find "$DST" -xdev -type f -name '*.php' -print0 | xargs -0 -r chmod 0644
      find "$DST" -xdev -type d -print0 | xargs -0 -r chmod 0755

      log "Done: $(date -Is)"
      exit 0
      DEPLOY
