deployment:
  tasks:
    - export SRC="$(pwd)"
    - export WEB="$HOME/public_html"
    - export CFG="$HOME/SiteConfigs"

    # Create targets
    - /bin/mkdir -p "$WEB" "$WEB/vendor" "$WEB/video" "$WEB/admin/uploads" "$CFG"

    # Deploy the public site to webroot
    - /usr/bin/rsync -a --delete "$SRC/public/" "$WEB/" || /bin/cp -a "$SRC/public/." "$WEB/"

    # Assets that must be publicly accessible (AdminLTE/Clarity/Login)
    - /usr/bin/rsync -a --delete "$SRC/vendor/" "$WEB/vendor/" || true

    # Non-public config outside webroot
    - /usr/bin/rsync -a "$SRC/config/" "$CFG/" || /bin/cp -a "$SRC/config/." "$CFG/"

    # Keep install.sql outside webroot (preferred path for the installer)
    - /bin/cp -af "$SRC/install.sql" "$CFG/install.sql"

    # Permissions
    - /bin/find "$WEB" -type d -exec /bin/chmod 755 {} \;
    - /bin/find "$WEB" -type f -exec /bin/chmod 644 {} \;
    - /bin/chmod 775 "$WEB/video" "$WEB/admin/uploads" || true
    - /bin/chmod 700 "$CFG" || true
    - /bin/chmod 600 "$CFG/db.local.php" || true
