---
deployment:
  tasks:
    # Adjust this if your docroot is different (e.g., a subdomain folder)
    - export SITE_ROOT="$HOME/public_html"
    - export REPO_ROOT="$(pwd)"

    # Update Overall
    # Ensure target folders exist
    - /bin/mkdir -p "$SITE_ROOT" "$SITE_ROOT/vendor" "$SITE_ROOT/video" "$SITE_ROOT/admin/uploads" "$HOME/config"

    # Deploy public/ to webroot
    - /usr/bin/rsync -a --delete --exclude=".git" --exclude=".cpanel.yml" "$REPO_ROOT/public/" "$SITE_ROOT/" || /bin/cp -a "$REPO_ROOT/public/." "$SITE_ROOT/"

    # Deploy vendor/ (needed for /vendor/clarity and AdminLTE assets)
    - /usr/bin/rsync -a --delete "$REPO_ROOT/vendor/" "$SITE_ROOT/vendor/" || ( /bin/mkdir -p "$SITE_ROOT/vendor" && /bin/cp -a "$REPO_ROOT/vendor/." "$SITE_ROOT/vendor/" )

    # Place config outside webroot so PHP includes ../config/*
    - /usr/bin/rsync -a "$REPO_ROOT/config/" "$HOME/config/" || /bin/cp -a "$REPO_ROOT/config/." "$HOME/config/"

    # Place install.sql where the installer expects it (~/install.sql)
    - /bin/cp -f "$REPO_ROOT/install.sql" "$HOME/install.sql"

    # Permissions (safe defaults for suPHP)
    - /bin/find "$SITE_ROOT" -type d -exec /bin/chmod 755 {} \;
    - /bin/find "$SITE_ROOT" -type f -exec /bin/chmod 644 {} \;
    - /bin/chmod 755 "$SITE_ROOT/video" "$SITE_ROOT/admin/uploads" || true
    - /bin/chmod 700 "$HOME/config" || true
    - /bin/chmod 600 "$HOME/config/db.local.php" || true
