---
deployment:
  tasks:
    # Paths provided by cPanel:
    #   $DEPLOYMENT_SOURCE -> repo checkout
    #   $DEPLOYMENT_TARGET -> docroot (e.g., /home/$USER/public_html)
    - export SRC="$DEPLOYMENT_SOURCE"
    - export DST="$DEPLOYMENT_TARGET"
    - echo "Deploy from $SRC to $DST"

    # Ensure persistent storage exists outside repo and is linked
    - export HOME="/home/$USER"
    - mkdir -p "$HOME/SiteStorage/media" "$HOME/SiteStorage/video"
    - if [ ! -e "$DST/media" ]; then ln -s "$HOME/SiteStorage/media" "$DST/media"; fi
    - if [ ! -e "$DST/video" ]; then ln -s "$HOME/SiteStorage/video" "$DST/video"; fi

    # Sync code but NEVER delete real uploads
    - rsync -a "$SRC/public/" "$DST/" \
        --exclude="media/***" --exclude="video/***" --exclude="uploads/***" \
        --delete-excluded --delete-after

    # Permissions (best-effort)
    - find "$DST" -type f -name "*.php" -exec chmod 0644 {} \;
    - find "$DST" -type d -exec chmod 0755 {} \;